spring:
  profiles: unit-test
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 
  jpa:
    properties:
      hibernate:
        format_sql: true
        
server:
  port: 8080
